URL_SERVICE = "https://275dc34f-0a11-4b1d-849a-1d1a3b2ee8bd.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
RODUCTS_KITS_PATH = "/api/v1/products/kits/"
